-- ============================================================
-- Clutch AI — Google Calendar Smart Sync Extensions
-- Migration: 015_smart_sync_extensions.sql
-- ============================================================

-- 1. Add source column to public.tasks table with source CHECK constraint
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_source_check;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_source_check CHECK (source IN ('manual', 'telegram', 'web', 'ai', 'google_calendar', 'gmail', 'calendar_ai'));

-- 2. Add sync_settings column to public.google_accounts table
ALTER TABLE public.google_accounts ADD COLUMN IF NOT EXISTS sync_settings JSONB DEFAULT '{
  "import_window": 90,
  "import_historical": false,
  "sync_recurring": false,
  "meeting_detection": true,
  "birthday_detection": false,
  "holiday_detection": false,
  "task_creation": "manual_suggest",
  "reminder_creation": true,
  "auto_ai_planning": false
}'::jsonb;

-- 3. Mark existing calendar-linked tasks with source = 'google_calendar'
UPDATE public.tasks
  SET source = 'google_calendar'
  WHERE id IN (
    SELECT DISTINCT task_id FROM public.calendar_events WHERE event_type = 'external' AND task_id IS NOT NULL
  ) OR description LIKE 'Generated by Clutch AI for event%';

-- 4. Archive calendar-linked tasks older than 30 days
UPDATE public.tasks
  SET status = 'archived'
  WHERE source = 'google_calendar'
    AND created_at < now() - INTERVAL '30 days';
